// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// Calls each activated plugin's bridge-class register() at startup, then
// hands the Activity to any bridge implementing MobActivityAware and records
// any bridge implementing MobPermissionProvider; invoked from
// MainActivity.onCreate as registerAll(this).
package io.mob.plugin

import android.app.Activity

object MobPluginBootstrap {
    private val permissionProviders = mutableListOf<MobPermissionProvider>()

    @JvmStatic
    fun registerAll(activity: Activity) {
        io.mob.bluetooth.MobBluetoothBridge.register()
        handOff(io.mob.bluetooth.MobBluetoothBridge, activity)
        collectPermissionProvider(io.mob.bluetooth.MobBluetoothBridge)
        io.mob.zigextras.MobZigExtrasBridge.register()
        handOff(io.mob.zigextras.MobZigExtrasBridge, activity)
        collectPermissionProvider(io.mob.zigextras.MobZigExtrasBridge)
        io.mob.demoperm.MobDemoPermBridge.register()
        handOff(io.mob.demoperm.MobDemoPermBridge, activity)
        collectPermissionProvider(io.mob.demoperm.MobDemoPermBridge)
        io.mob.location.MobLocationBridge.register()
        handOff(io.mob.location.MobLocationBridge, activity)
        collectPermissionProvider(io.mob.location.MobLocationBridge)
        io.mob.camera.MobCameraBridge.register()
        handOff(io.mob.camera.MobCameraBridge, activity)
        collectPermissionProvider(io.mob.camera.MobCameraBridge)
        io.mob.screencast.MobScreencastBridge.register()
        handOff(io.mob.screencast.MobScreencastBridge, activity)
        collectPermissionProvider(io.mob.screencast.MobScreencastBridge)
    }

    // Returns the first plugin-supplied Android permission mapping for `cap`,
    // or null if no activated plugin provides this capability. Core
    // MobBridge.request_permission consults this in its `else` branch.
    @JvmStatic
    fun permissionsFor(cap: String): Array<String>? {
        for (provider in permissionProviders) {
            val perms = provider.permissionsFor(cap)
            if (perms != null) return perms
        }
        return null
    }

    // Hands the Activity to a bridge that opts in via MobActivityAware.
    private fun handOff(bridge: Any, activity: Activity) {
        (bridge as? MobActivityAware)?.setActivity(activity)
    }

    // Records a bridge that opts in via MobPermissionProvider so core
    // MobBridge.request_permission can fall through to it for a capability
    // core no longer knows about.
    private fun collectPermissionProvider(bridge: Any) {
        (bridge as? MobPermissionProvider)?.let {
            if (!permissionProviders.contains(it)) permissionProviders.add(it)
        }
    }
}
