// Permission-registry demo plugin bridge (Android side).
//
// Implements io.mob.plugin.MobPermissionProvider (generated by mob_dev into the
// app Kotlin sourceSet at build time). MobPluginBootstrap.registerAll collects
// it, and core MobBridge.request_permission falls through to permissionsFor for
// the :demo_perm capability core knows nothing about.
//
// :demo_perm maps to INTERNET — a normal (install-time, always-granted)
// permission — so checkSelfPermission passes and core delivers
// {:permission, :demo_perm, :granted} immediately, proving the dispatch chain
// without an OS dialog. register() is a no-op: this provider is pure Kotlin and
// needs no native jclass caching.
package io.mob.demoperm

import io.mob.plugin.MobPermissionProvider

object MobDemoPermBridge : MobPermissionProvider {
    @JvmStatic
    fun register() {
        // Pure-Kotlin permission provider; nothing to cache natively.
    }

    override fun permissionsFor(cap: String): Array<String>? =
        if (cap == "demo_perm") arrayOf("android.permission.INTERNET") else null
}
